[build]
  publish = "public"

[[headers]]
  for = "/resume/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
